/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1b",
        "error-container": "#93000a",
        "on-secondary": "#00363a",
        "surface-container-highest": "#353534",
        "surface-tint": "#adc6ff",
        "secondary-container": "#00f1fe",
        "on-tertiary-fixed": "#2d1600",
        "surface-bright": "#3a3939",
        "secondary": "#ddfcff",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#004f54",
        "surface-container": "#201f1f",
        "on-tertiary": "#4b2800",
        "on-tertiary-container": "#412200",
        "tertiary-fixed": "#ffdcbf",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#c1c6d7",
        "on-primary-fixed-variant": "#004493",
        "on-secondary-container": "#006a70",
        "outline-variant": "#414755",
        "tertiary-fixed-dim": "#ffb874",
        "inverse-surface": "#e5e2e1",
        "primary-fixed-dim": "#adc6ff",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
        "inverse-on-surface": "#313030",
        "on-error": "#690005",
        "tertiary-container": "#d47b00",
        "secondary-fixed-dim": "#00dbe7",
        "primary": "#adc6ff",
        "primary-fixed": "#d8e2ff",
        "surface-container-high": "#2a2a2a",
        "on-primary-container": "#00285c",
        "surface": "#131313",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#001a41",
        "error": "#ffb4ab",
        "secondary-fixed": "#74f5ff",
        "tertiary": "#ffb874",
        "on-tertiary-fixed-variant": "#6a3b00",
        "background": "#131313",
        "inverse-primary": "#005bc1",
        "on-primary": "#002e69",
        "outline": "#8b90a0",
        "on-secondary-fixed": "#002022",
        "primary-container": "#4b8eff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "touch-target-min": "48px",
        "stack-gap": "16px",
        "grid-gutter": "12px",
        "container-padding": "20px",
        "safe-area-bottom": "34px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "metric-huge": ["Inter", "sans-serif"],
        "metric-md": ["Inter", "sans-serif"],
        "mono-data": ["Geist", "monospace"],
        "label-caps": ["Geist", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
